version: '3'

volumes:
  local_postgres_data: { }
  local_postgres_data_backups: { }

services:
  postgres:
    image: postgres
    container_name: my_flask_app_postgres_local
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - .env
    ports:
      - "5432:5432"
