"""initial migrate

Revision ID: 7c9453b21098
Revises: 
Create Date: 2024-09-11 19:04:02.564716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c9453b21098'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('categoryid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('categoryname', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('categoryid')
    )
    op.create_table('customers',
    sa.Column('customerid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customername', sa.String(length=255), nullable=True),
    sa.Column('contactname', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('postalcode', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('customerid')
    )
    op.create_table('employees',
    sa.Column('employeeid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lastname', sa.String(length=255), nullable=True),
    sa.Column('firstname', sa.String(length=255), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('employeeid')
    )
    op.create_table('shippers',
    sa.Column('shipperid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shippername', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('shipperid')
    )
    op.create_table('suppliers',
    sa.Column('supplierid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('suppliername', sa.String(length=255), nullable=True),
    sa.Column('contactname', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('postalcode', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('supplierid')
    )
    op.create_table('orders',
    sa.Column('orderid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customerid', sa.Integer(), nullable=True),
    sa.Column('employeeid', sa.Integer(), nullable=True),
    sa.Column('orderdate', sa.Date(), nullable=True),
    sa.Column('shipperid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customerid'], ['customers.customerid'], ),
    sa.ForeignKeyConstraint(['employeeid'], ['employees.employeeid'], ),
    sa.ForeignKeyConstraint(['shipperid'], ['shippers.shipperid'], ),
    sa.PrimaryKeyConstraint('orderid')
    )
    op.create_table('products',
    sa.Column('productid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('productname', sa.String(length=255), nullable=True),
    sa.Column('supplierid', sa.Integer(), nullable=True),
    sa.Column('categoryid', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['categoryid'], ['categories.categoryid'], ),
    sa.ForeignKeyConstraint(['supplierid'], ['suppliers.supplierid'], ),
    sa.PrimaryKeyConstraint('productid')
    )
    op.create_table('order_details',
    sa.Column('orderdetailid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('orderid', sa.Integer(), nullable=True),
    sa.Column('productid', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['orderid'], ['orders.orderid'], ),
    sa.ForeignKeyConstraint(['productid'], ['products.productid'], ),
    sa.PrimaryKeyConstraint('orderdetailid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_details')
    op.drop_table('products')
    op.drop_table('orders')
    op.drop_table('suppliers')
    op.drop_table('shippers')
    op.drop_table('employees')
    op.drop_table('customers')
    op.drop_table('categories')
    # ### end Alembic commands ###
